pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub_id')
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh './scripts/build.sh'
            }
        }
        stage('Test') {
            steps {
                sh './scripts/test.sh'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t opancheliuga/nodeapp:${env.BRANCH_NAME}-${env.BUILD_NUMBER} .'
            }
        }
        stage('Push Docker Image') {
            steps {
                    sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                    sh 'docker push opancheliuga/nodeapp:${env.BRANCH_NAME}-${env.BUILD_NUMBER}'
            }
        }
    }
}
